[install]
# 使用阿里云加速仓库，仓库地址可从阿里云官方获取，地址为 https://developer.aliyun.com/mirror/
registry = "https://registry.npmmirror.com/"


# Bun 加速仓库配置参考官网 https://bun.net.cn/docs/runtime/bunfig
# https://bun.net.cn/docs/runtime/bunfig
